/**
 * Audio Loader and Management System
 * Handles loading, caching, and playing audio files
 */

export interface AudioTrack {
  id: string;
  name: string;
  path: string;
  duration: number; // in seconds
  category: 'focus' | 'relaxation' | 'deep' | 'ambient' | 'binaural';
  frequency?: string;
  benefits: string[];
}

// Audio track catalog
export const audioTracks: AudioTrack[] = [
  // Focus Waves
  {
    id: 'alpha-focus',
    name: 'Alpha Focus Wave',
    path: '/audio/focus/alpha-focus.wav',
    duration: 60, // 1 minute (for testing - actual is 60 seconds)
    category: 'focus',
    frequency: '8-12 Hz',
    benefits: ['Enhanced concentration', 'Mental clarity', 'Reduced distractions']
  },
  {
    id: 'beta-focus',
    name: 'Beta Focus Wave',
    path: '/audio/focus/beta-focus.wav',
    duration: 60, // 1 minute
    category: 'focus',
    frequency: '13-30 Hz',
    benefits: ['Active thinking', 'Problem solving', 'Alertness']
  },
  {
    id: 'gamma-focus',
    name: 'Gamma Focus Wave',
    path: '/audio/focus/gamma-focus.wav',
    duration: 60, // 1 minute
    category: 'focus',
    frequency: '30-100 Hz',
    benefits: ['Peak performance', 'Cognitive enhancement', 'Information processing']
  },
  
  // Relaxation Waves
  {
    id: 'theta-relax',
    name: 'Theta Relaxation',
    path: '/audio/relax/theta-relax.wav',
    duration: 60, // 1 minute
    category: 'relaxation',
    frequency: '4-8 Hz',
    benefits: ['Deep relaxation', 'Stress relief', 'Meditation']
  },
  {
    id: 'alpha-relax',
    name: 'Alpha Calm',
    path: '/audio/relax/alpha-calm.wav',
    duration: 60, // 1 minute
    category: 'relaxation',
    frequency: '8-12 Hz',
    benefits: ['Peaceful state', 'Anxiety reduction', 'Mental rest']
  },
  
  // Deep Focus
  {
    id: 'deep-focus',
    name: 'Deep Focus Session',
    path: '/audio/deep/deep-focus.wav',
    duration: 60, // 1 minute
    category: 'deep',
    frequency: '14-20 Hz',
    benefits: ['Prolonged concentration', 'Flow state', 'Maximum productivity']
  },
  {
    id: 'study-wave',
    name: 'Study Wave',
    path: '/audio/deep/study-wave.wav',
    duration: 60, // 1 minute
    category: 'deep',
    frequency: '12-18 Hz',
    benefits: ['Learning enhancement', 'Memory retention', 'Information absorption']
  },
  
  // Binaural Beats (generated in real-time, no file needed)
  {
    id: 'binaural-alpha',
    name: 'Alpha Binaural Beat',
    path: '', // Generated by Web Audio API
    duration: 1500,
    category: 'binaural',
    frequency: '8-12 Hz',
    benefits: ['Relaxed focus', 'Creativity', 'Reduced anxiety']
  },
  {
    id: 'binaural-beta',
    name: 'Beta Binaural Beat',
    path: '', // Generated by Web Audio API
    duration: 1500,
    category: 'binaural',
    frequency: '13-30 Hz',
    benefits: ['Active concentration', 'Problem solving', 'Energy']
  },
  {
    id: 'binaural-theta',
    name: 'Theta Binaural Beat',
    path: '', // Generated by Web Audio API
    duration: 1800,
    category: 'binaural',
    frequency: '4-8 Hz',
    benefits: ['Deep meditation', 'Intuition', 'Subconscious access']
  },
  {
    id: 'binaural-delta',
    name: 'Delta Binaural Beat',
    path: '', // Generated by Web Audio API
    duration: 3600,
    category: 'binaural',
    frequency: '0.5-4 Hz',
    benefits: ['Deep sleep', 'Healing', 'Recovery']
  },
  {
    id: 'binaural-gamma',
    name: 'Gamma Binaural Beat',
    path: '', // Generated by Web Audio API
    duration: 1200,
    category: 'binaural',
    frequency: '30-100 Hz',
    benefits: ['Peak cognition', 'Heightened awareness', 'Information processing']
  }
];

// Ambient sounds catalog
export const ambientSounds = [
  {
    id: 'rain',
    name: 'Rain',
    path: '/audio/ambient/rain.wav',
    description: 'Gentle rainfall ambience',
    color: '#73daca'
  },
  {
    id: 'ocean',
    name: 'Ocean Waves',
    path: '/audio/ambient/ocean.wav',
    description: 'Calming ocean waves',
    color: '#7aa2f7'
  },
  {
    id: 'wind',
    name: 'Wind',
    path: '/audio/ambient/wind.wav',
    description: 'Soft wind sounds',
    color: '#bb9af7'
  },
  {
    id: 'whistle',
    name: 'Whistle',
    path: '/audio/ambient/whistle.wav',
    description: 'Melodic whistle tune',
    color: '#ff9e64'
  },
  {
    id: 'whitenoise',
    name: 'White Noise',
    path: '/audio/ambient/white-noise.wav',
    description: 'Pure static masking',
    color: '#c0caf5'
  },
  {
    id: 'forest',
    name: 'Forest',
    path: '/audio/ambient/forest.wav',
    description: 'Natural forest ambience',
    color: '#9ece6a'
  },
  {
    id: 'nature',
    name: 'Nature',
    path: '/audio/ambient/nature.wav',
    description: 'Mixed nature sounds',
    color: '#7dcfff'
  }
];

class AudioLoader {
  private audioContext: AudioContext | null = null;
  private bufferCache: Map<string, AudioBuffer> = new Map();
  private loadingPromises: Map<string, Promise<AudioBuffer>> = new Map();

  constructor() {
    if (typeof window !== 'undefined') {
      this.initAudioContext();
    }
  }

  private initAudioContext() {
    try {
      this.audioContext = new (window.AudioContext || (window as any).webkitAudioContext)();
    } catch (error) {
      console.error('Web Audio API not supported', error);
    }
  }

  /**
   * Load an audio file and cache it
   */
  async loadAudio(url: string): Promise<AudioBuffer> {
    if (!this.audioContext) {
      throw new Error('AudioContext not initialized');
    }

    // Return cached buffer if available
    if (this.bufferCache.has(url)) {
      return this.bufferCache.get(url)!;
    }

    // Return existing loading promise if already loading
    if (this.loadingPromises.has(url)) {
      return this.loadingPromises.get(url)!;
    }

    // Start loading
    const loadPromise = this.fetchAndDecodeAudio(url);
    this.loadingPromises.set(url, loadPromise);

    try {
      const buffer = await loadPromise;
      this.bufferCache.set(url, buffer);
      this.loadingPromises.delete(url);
      return buffer;
    } catch (error) {
      this.loadingPromises.delete(url);
      throw error;
    }
  }

  private async fetchAndDecodeAudio(url: string): Promise<AudioBuffer> {
    if (!this.audioContext) {
      throw new Error('AudioContext not initialized');
    }

    try {
      const response = await fetch(url);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const arrayBuffer = await response.arrayBuffer();
      return await this.audioContext.decodeAudioData(arrayBuffer);
    } catch (error) {
      console.error(`Failed to load audio from ${url}:`, error);
      throw error;
    }
  }

  /**
   * Preload multiple audio files
   */
  async preloadAudio(urls: string[]): Promise<void> {
    const promises = urls.map(url => this.loadAudio(url).catch(err => {
      console.warn(`Failed to preload ${url}:`, err);
      return null;
    }));
    await Promise.all(promises);
  }

  /**
   * Get cached buffer
   */
  getBuffer(url: string): AudioBuffer | null {
    return this.bufferCache.get(url) || null;
  }

  /**
   * Clear cache
   */
  clearCache(): void {
    this.bufferCache.clear();
  }

  /**
   * Get audio context
   */
  getContext(): AudioContext | null {
    return this.audioContext;
  }
}

// Singleton instance
let audioLoaderInstance: AudioLoader | null = null;

export const getAudioLoader = (): AudioLoader => {
  if (!audioLoaderInstance) {
    audioLoaderInstance = new AudioLoader();
  }
  return audioLoaderInstance;
};

// Helper function to get track by id
export const getTrackById = (id: string): AudioTrack | undefined => {
  return audioTracks.find(track => track.id === id);
};

// Helper function to get tracks by category
export const getTracksByCategory = (category: AudioTrack['category']): AudioTrack[] => {
  return audioTracks.filter(track => track.category === category);
};

// Helper function to get all available tracks
export const getAllTracks = (): AudioTrack[] => {
  return audioTracks;
};

export default AudioLoader;
